const productsCatalog = [
    { 
        id: 'el1',
        name: 'Плов Чайханский', 
        price: 246, 
        weight: 250, 
        img: 'src/img/pilaf.png', 
        imgBig: 'src/img/pilaf-big.png', 
        description: 'Камчатский краб, авокадо, свежие овощи и цитрусовый...',
        descriptionComposition: 'Камчатский краб, авокадо, свежие овощи и цитрусовый сок.',
        calories: 650,
        squirrels: 34,
        fats: 60,
        carbohydrates: 12,
    },
    { 
        id: 'el2', 
        name: 'Шаверма', 
        price: 246, 
        weight: 336, 
        img: 'src/img/shawarma.png', 
        imgBig: 'src/img/shawarma-big.png', 
        description: 'Мясо оленя, авокадо, свежие овощи и цитрусовый...', 
        descriptionComposition: 'Салат, микс мясо, зелень и чуточку лимона.',
        calories: 600,
        squirrels: 30,
        fats: 70,
        carbohydrates: 16,
    },
    {
        id: 'el3',
        name: 'Шашлык', 
        price: 656, 
        weight: 250, 
        img: 'src/img/barbecue.png', 
        imgBig: 'src/img/barbecue-big.png',
        description: 'Бычок в основе, авокадо, свежие овощи и цитрусовый...',  
        descriptionComposition: 'мягкие прожаренные кусочки мяса и свежие овощи.',
        calories: 550,
        squirrels: 64,
        fats: 30,
        carbohydrates: 17,
    },
    { 
        id: 'el4',
        name: 'Судак', 
        price: 226, 
        weight: 250, 
        img: 'src/img/zander.png', 
        imgBig: 'src/img/zander-big.png',
        description: 'Лошадиная сила, авокадо, свежие овощи и цитрусовый...', 
        descriptionComposition: 'Рыба, краб, свежие овощи и сок лимона.',
        calories: 690,
        squirrels: 30,
        fats: 48,
        carbohydrates: 10,
    },
    { 
        id: 'el5', 
        name: 'Манты', 
        price: 326, 
        weight: 250, 
        img: 'src/img/manti.png', 
        imgBig: 'src/img/manti-big.png',
        description: 'Мясо мамонта, краб, авокадо, свежие овощи и цитрусовые...', 
        descriptionComposition: 'Тесто, язык, свежие овощи и фрукты.',
        calories: 690,
        squirrels: 24,
        fats: 55,
        carbohydrates: 19,
    },
    { 
        id: 'el6', 
        name: 'Хашлама', 
        price: 246, 
        weight: 250, 
        img: 'src/img/khaslama.png', 
        imgBig: 'src/img/khashlama-big.png',
        description: 'Индейка на пару, макароны, свежие овощи и цитрусовый сок...', 
        descriptionComposition: 'Орегано, мясо, специи, свежие овощи и цитрусовый.',
        calories: 610,
        squirrels: 24,
        fats: 50,
        carbohydrates: 2,
    },
    { 
        id: 'el7', 
        name: 'Бешбармак', 
        price: 446, 
        weight: 250, 
        img: 'src/img/beshbarmak.png', 
        imgBig: 'src/img/beshbarmak-big.png',
        description: 'Курица, авокадо, свежие овощи и цитрусовый сок...',
        descriptionComposition: 'Специи, мясо, авокадо, и цитрусовые.',
        calories: 350,
        squirrels: 64,
        fats: 22,
        carbohydrates: 20,
    },
    { 
        id: 'el8', 
        name: 'Ковурма', 
        price: 246, 
        weight: 250, 
        img: 'src/img/kovurma.png', 
        imgBig: 'src/img/kovurma-big.png',
        description: 'Рыба океана, авокадо, свежие овощи и цитрусовый сок...',
        descriptionComposition: 'Рис, мясо, свежая морковь и рассол.',
        calories: 450,
        squirrels: 24,
        fats: 30,
        carbohydrates: 18,
    },
    
];