const productsCatalog = [
    { 
        id: 'el1',
        name: 'Плов Чайханский', 
        price: 246, 
        weight: 250, 
        img: 'src/img/pilaf.png', 
        description: 'Камчатский краб, авокадо, свежие овощи и цитрусовый...',
    },
    { 
        id: 'el2', 
        name: 'Шаверма', 
        price: 246, 
        weight: 250, 
        img: 'src/img/shawarma.png', 
        description: 'Камчатский краб, авокадо, свежие овощи и цитрусовый...', 
    },
    {
        id: 'el3',
        name: 'Шашлык', 
        price: 656, 
        weight: 250, 
        img: 'src/img/barbecue.png', 
        description: 'Камчатский краб, авокадо, свежие овощи и цитрусовый...',  
    },
    { 
        id: 'el4',
        name: 'Судак', 
        price: 226, 
        weight: 250, 
        img: 'src/img/zander.png', 
        description: 'Камчатский краб, авокадо, свежие овощи и цитрусовый...', 
    },
    { 
        id: 'el5', 
        name: 'Манты', 
        price: 326, 
        weight: 250, 
        img: 'src/img/manti.png', 
        description: 'Камчатский краб, авокадо, свежие овощи и цитрусовый...', 
    },
    { 
        id: 'el6', 
        name: 'Шаверма', 
        price: 246, 
        weight: 250, 
        img: 'src/img/shawarma.png', 
        description: 'Камчатский краб, авокадо, свежие овощи и цитрусовый...', 
    },
    { 
        id: 'el7', 
        name: 'Бешбармак', 
        price: 446, 
        weight: 250, 
        img: 'src/img/beshbarmak.png', 
        description: 'Камчатский краб, авокадо, свежие овощи и цитрусовый...',
    },
    { 
        id: 'el8', 
        name: 'Ковурма', 
        price: 246, 
        weight: 250, 
        img: 'src/img/kovurma.png', 
        description: 'Камчатский краб, авокадо, свежие овощи и цитрусовый...',
    },
    
];